version: '3'

services:
  game:
    image: tower-game
    networks:
      - game-network

    volumes:
      - game-data:/app/data
  
networks:
  game-network:
    driver: bridge

volumes:
  game-data:
    driver: local