---
- name: Aprovisionar VM con políticas de seguridad
  hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  tasks:
    - import_tasks: tasks/pam_pwquality.yml
    - import_tasks: tasks/user_and_group.yml