name: Empaquetar Juego

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with: 
        registry: ghcr.io
        user: ${{ github.actor }}
        password: ${{ secrets.TOKEN_DEPLOY }}
        

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.7'

    - name: Install dependencies
      run: | 
           python --version
           python -m pip install --upgrade pip setuptools wheel
    
    - name: Build Docker image
      run: |
        docker build . --tag ghcr.io/siok20/CC3S2-Actividades:latest
        docker push ghcr.io/siok20/CC3S2-Actividades:latest
      working-directory: Actividad-9
 